# Identifiants obligatoires récupérés sur l'interface SonarQube Cloud
sonar.organization=jamjoum
sonar.projectKey=jamjoum

# Chemins vers les fichiers sources (relatifs à la racine)
sonar.sources=src

# Encodage des fichiers sources
sonar.sourceEncoding=UTF-8